[package]
name = "voting_v2"
version = "1.0.0"
authors = []

[addresses]
module_address="0xd503828907081aaf564ebecea6a2a470538c1892746d7f7574ae72a2d9a1fce7"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
